/*
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCreateLanguageScopeProvider extends DelegatingScopeProvider {
}
