/*
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech.ui.tests;

import com.google.inject.Injector;
import fr.unice.si5.polytech.createlanguage.concretesyntax.ui.internal.ConcretesyntaxActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CreateLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ConcretesyntaxActivator.getInstance().getInjector("fr.unice.si5.polytech.CreateLanguage");
	}

}
