/**
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech.ui;

import fr.unice.si5.polytech.ui.AbstractCreateLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CreateLanguageUiModule extends AbstractCreateLanguageUiModule {
  public CreateLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
