/*
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CreateLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/unice/si5/polytech/parser/antlr/internal/InternalCreateLanguage.tokens");
	}
}
