/*
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech.parser.antlr;

import com.google.inject.Inject;
import fr.unice.si5.polytech.parser.antlr.internal.InternalCreateLanguageParser;
import fr.unice.si5.polytech.services.CreateLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CreateLanguageParser extends AbstractAntlrParser {

	@Inject
	private CreateLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCreateLanguageParser createParser(XtextTokenStream stream) {
		return new InternalCreateLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CreateProgram";
	}

	public CreateLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CreateLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
