/**
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech;

import fr.unice.si5.polytech.CreateLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CreateLanguageStandaloneSetup extends CreateLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new CreateLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
