/**
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech;

import fr.unice.si5.polytech.AbstractCreateLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CreateLanguageRuntimeModule extends AbstractCreateLanguageRuntimeModule {
}
