/**
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech.ui.contentassist;

import fr.unice.si5.polytech.ui.contentassist.AbstractCreateLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CreateLanguageProposalProvider extends AbstractCreateLanguageProposalProvider {
}
