/*
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CreateLanguageRuntimeModule extends AbstractCreateLanguageRuntimeModule {
}
