/**
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech.ide;

import fr.unice.si5.polytech.ide.AbstractCreateLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CreateLanguageIdeModule extends AbstractCreateLanguageIdeModule {
}
