/**
 * generated by Xtext 2.14.0
 */
package fr.unice.si5.polytech.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.unice.si5.polytech.CreateLanguageRuntimeModule;
import fr.unice.si5.polytech.CreateLanguageStandaloneSetup;
import fr.unice.si5.polytech.ide.CreateLanguageIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CreateLanguageIdeSetup extends CreateLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    CreateLanguageRuntimeModule _createLanguageRuntimeModule = new CreateLanguageRuntimeModule();
    CreateLanguageIdeModule _createLanguageIdeModule = new CreateLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_createLanguageRuntimeModule, _createLanguageIdeModule));
  }
}
